apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
    type: front-end
spec:
  template:
    metadata:
      name: nodejsapp-pod
      labels:
        app: nodejsapp
        type: front-end
    spec:
      containers:
        - name: nodejsapp-erp
          image: "achtacht/example-todo-frontend:latest"
  replicas: 2
  selector:
    matchLabels:
      type: front-end

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejsapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30000
